### ISSUE TITLE
Could you share the scripts for preprocessing the Human3.6M dataset

### ISSUE THREAD

**Issue by huge123** [bastianwandt/RepNet#1]
Thanks for opening source, I have downloaded the human3.6m dataset from offical website, but I am not quite clear about aligning the 3D pose to a template as described in the paper, so I wonder if you can share the scripts for preprocessing the dataset?

Looking forward to your reply.

**Comment by laihuaijing** [comment]
请问你解决了吗？能麻烦分享一下吗？ @huge123
