### ISSUE TITLE
question about data pre-processing

### ISSUE THREAD

**Issue by sdxass** [bastianwandt/RepNet#2]
Hi,

Thank you for your wonderful work. I want to ask why did you preprocess inputs 2d pose like this:
https://github.com/bastianwandt/RepNet/blob/7b9185cadd12f850e9fa1754505fca68c34be4ed/train_repnet.py#L174

Looking forward to your response.

**Comment by bastianwandt** [comment]
Hi,

the origin of the image coordinates is in the upper left corner. That means all 2d joint coordinates are "flipped" at the x-axis. Since the 2d poses are mean centered the flip can be done by multiplying with -1. Hope that helps.

**Comment by sdxass** [comment]
Thank you for your response.
